name: 'Unit Tests, Coverage'

on:
  workflow_dispatch:
  push:
    branches: ['master', 'develop', 'main']
  pull_request:
    branches: ['master', 'develop', 'main']
    types: ['opened', 'reopened', 'synchronize']

jobs:
  build:
    name: 'Unit Tests, Coverage'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Execute unit tests
        env:
          HUSKY: 0
        run: |
          npm ci
          npm run test:ci
          npm run check:lint:ci

